version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  app:
    build: .
    ports:
      - '1234:1234'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRETKEY: ${SECRETKEY}
      ESKIZ_USER_EMAIL: ${ESKIZ_USER_EMAIL}
      ESKIZ_USER_PASSWoRD: ${ESKIZ_USER_PASSWoRD}
      ESKIZ_USER_TOKEN: ${ESKIZ_USER_TOKEN}
      REDIS_URL: redis://redis:6379
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - db
      - redis
    command: >
      sh -c "npx prisma migrate dev && node dist/main"

  prisma:
    image: node:22
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "npm install -g pnpm && pnpm install && pnpm prisma studio"
    ports:
      - '5555:5555'
    depends_on:
      - db

volumes:
  postgres_data:
